sorare_ae_interview:
  outputs:
    dev:
      account: UMGSHNJ-GE28364
      database: AE_INTERVIEW
      password: tEYxqh2gD7JUfj2zADzy
      role: INTERVIEWEE
      schema: ANALYTICS
      threads: 8
      type: snowflake
      user: AE_CANDIDATE
      warehouse: ANALYSIS
  target: dev